---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-user-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: <IAM Role ARN>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-user-role
  namespace: default
rules:
- apiGroups: [""]
  verbs: ["get", "list", "delete", "deletecollection"]
  resources: ["pods", "pods/log"]
- apiGroups: ["batch"]
  verbs: ["create", "get", "delete"]
  resources: ["jobs", "jobs/status"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-user-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-user-role
subjects:
  - kind: ServiceAccount
    name: job-user-sa
    namespace: default
